single_encoder:
  model_name_or_path: bert-base-multilingual-cased
  save_path: model_output/{date_of_training}_{mode}_{language}_training/
  val_steps: 20
dual_encoder:
  query_model_name_or_path: bert-base-multilingual-cased
  doc_model_name_or_path: bert-base-multilingual-cased
  save_path: model_output/{date_of_training}_{mode}_{language}_training/
  val_steps: 20
